Repository InstitutG4/app-traveled, pull requests merged in 2018-05, with the labels that each got.

#351 feat(font): ajouter les fonts
  src/fonts/Proxima-Nova-Alt-Regular.otf
  src/fonts/Proxima-Nova-Alt-Thin.otf
  src/index.css
Labels: review

#371 #366 Center header title
  src/components/Header.js
Labels: review

#372 #201 Format dates
  src/components/DateDisplay.js
  src/components/ListItemSpending.js
  src/utils/dateTimeFormatter.js
Labels: review

#370 #360 #362 bug message erreurs : Erreurs en français et suppression des erreurs au changement de page
  src/App.js
  src/pages/Authentication/Login.js
  src/pages/Authentication/Registration.js
  src/stores/UserStore.js
Labels: review

#373 Détail d'un voyage
  src/components/ListItemVoyage.js
  src/components/TravelMenuDrawer.js
  src/pages/Travel/TravelDetailPage.js
  src/stores/UserStore.js
Labels: Back, Développement, review

#338 feat(travel): create travel 3
  src/components/Input.js
  src/pages/Travel/TravelCreationPage.js
  src/pages/Travel/TravelCreationPageThree.js
  src/stores/TravelStore.js
Labels: modifications attendues, review

#382 #277 front création d'un voyage 1
  src/components/Carousel.js
  src/components/Header.js
  src/img/imgVoyages/Aurore.jpg
  src/img/imgVoyages/Champ.jpg
  src/img/imgVoyages/Foret.jpg
  src/img/imgVoyages/Montain.jpg
  src/img/imgVoyages/Neige.jpg
  src/img/imgVoyages/Plage.jpg
  src/img/imgVoyages/Ville.jpg
  src/pages/Travel/TravelCreationPage.js
  src/pages/Travel/TravelCreationPageOne.js
Labels: review

#385 #263 #264 MENU modifier un voyage
  package.json
  src/components/Link.js
  src/components/TravelDetailEditMenu.js
  src/components/TravelDetailEditMenuItem.js
  src/index.js
  src/pages/Travel/TravelDetailPage.js
  yarn.lock
Labels: review

#378 #365 Inscription : Avatar placeholder
  src/components/Avatar.js
  src/components/DatePicker.js
  src/components/ImageUpload.js
  src/components/ListItemVoyage.js
  src/pages/Authentication/Registration.js
  src/pages/Travel/TravelDetailPage.js
Labels: Not merged, review

#387 275 355 add spending BACK Ajout de dépenses + BACK Modale ajouter un participant
  .editorconfig
  .gitignore
  package.json
  src/App.js
  src/components/AddUsersDialog.js
  src/components/Header.js
  src/components/ListItemSpending.js
  src/components/TravelMenuDrawer.js
  src/pages/Spending/SpendingCreation.js
  src/pages/Spending/SpendingPage.js
  src/pages/Travel/TravelDetailPage.js
  src/stores/RootStore.js
  src/stores/SpendingStore.js
  src/stores/TravelStore.js
  yarn.lock
Labels: review

#377 Rename and refactor components directory
  src/components/ColorSquare.js
  src/components/Header.js
  src/components/LabelBottomNavigation.js
  src/components/SideMenu.js
  src/components/buttons/BackButton.js
  src/components/buttons/Button.js
  src/components/buttons/CheckboxButton.js
  src/components/buttons/FixedActionButton.js
  src/components/buttons/MainButton.js
  src/components/buttons/RadioButton.js
  src/components/buttons/SecondaryButton.js
  src/components/datetime/DateDisplay.js
  src/components/datetime/DatePicker.js
  src/components/datetime/TimePicker.js
  src/index.css
  src/pages/Authentication/Login.js
  src/pages/Authentication/Registration.js
  src/pages/Spending/SpendingCreation.js
  src/pages/Spending/SpendingPage.js
  src/pages/Spending/components/ListItemSpending.js
  src/pages/Travel/TravelCreationPageOne.js
  src/pages/Travel/TravelCreationPageThree.js
  src/pages/Travel/TravelDetailPage.js
  src/pages/Travel/TravelPage.js
  src/pages/Travel/components/ListItemVoyage.js
  src/pages/Travel/components/ModuleIcon.js
  src/pages/Travel/components/SelectTravelModules.js
  src/pages/Travel/components/TravelDetailEditMenu.js
  src/pages/Travel/components/TravelDetailEditMenuItem.js
  src/pages/Travel/components/TravelMenuDrawer.js
Labels: review

#404 255 listes depenses
  src/components/LabelBottomNavigation.js
  src/pages/Spending/SpendingCreation.js
  src/pages/Spending/SpendingPage.js
  src/stores/SpendingStore.js
Labels: review

#386 279 front creeation voyage3 participants
  src/index.css
  src/index.js
  src/pages/Travel/TravelCreationPageThree.js
Labels: Can i merge ?, review

#400 233 front détail voyage
  package.json
  src/components/AddUsersDialog.js
  src/img/backgrounds/module_background.jpg
  src/img/backgrounds/module_background.png
  src/index.css
  src/pages/Travel/TravelDetailPage.js
  tsconfig.json
  yarn.lock
Labels: review

#374 correction message d'erreur trop long
  src/components/Input.js
  src/components/datetime/DatePicker.js
  src/pages/Authentication/Login.js
  src/pages/Authentication/Registration.js
Labels: modifications attendues

#405 Correction Design Menu Modification d'un voyage
  src/index.css
  src/pages/Travel/components/TravelDetailEditMenu.js
  src/pages/Travel/components/TravelDetailEditMenuItem.js
Labels: Can i merge ?, review

#408 357 back modifier depenses
  src/App.js
  src/components/AddUsersDialog.js
  src/pages/Spending/SpendingCreation.js
  src/pages/Spending/SpendingPage.js
  src/pages/Spending/components/ListItemSpending.js
  src/stores/SpendingStore.js
Labels: review

#413 Component card depense#296
  package.json
  src/index.css
  src/pages/Spending/SpendingPage.js
  src/pages/Spending/components/ListItemSpending.js
Labels: review
