Repository InstitutG4/app-traveled, pull requests merged in 2018-04, with the labels that each got.

#238 add primaryButton & SecondaryButton
  .vscode/settings.json
  src/components/Link.js
  src/components/MainButton.js
  src/components/SecondaryButton.js
  src/pages/Authentication/Authentication.js
Labels: dév FRONT

#259 #227 Bouton flottant (FAB)
  package.json
  src/App.js
  src/components/DateDisplay.js
  src/components/FixedActionButton.js
  src/pages/Authentication/Login.js
  src/pages/Authentication/Registration.js
Labels: dév FRONT, développement

#267 Ajout des Apis et des Stores pour toutes les Entités
  .vscode/settings.json
  src/api/HousingApi.js
  src/api/PromoCodeApi.js
  src/api/SpendingApi.js
  src/api/TransportApi.js
  src/stores/HousingStore.js
  src/stores/PromoCodeStore.js
  src/stores/SpendingStore.js
  src/stores/TransportStore.js
  src/stores/TravelStore.js
Labels: développement, modifications attendues, review

#306 create h1 & h2 in index.css
  src/index.css
Labels: dév FRONT

#274 Material UI Components : Buttons and ConfirmDeleteDialog
  src/App.js
  src/components/Button.js
  src/components/ConfirmDeleteDialog.js
  src/components/FixedActionButton.js
  src/components/Modal.js
  src/pages/Authentication/Login.js
  src/pages/Travel/TravelCreationPage.js
  src/pages/Travel/TravelPage.js
  src/stores/AppStore.js
  src/stores/TravelStore.js
Labels: développement, review

#313 Side Menu Modules Travel (Drawer)
  index.html
  src/api/ModuleApi.js
  src/components/Header.js
  src/components/ModuleIcon.js
  src/components/TravelMenuDrawer.js
  src/img/backgrounds/module_background.jpg
  src/img/backgrounds/module_background.png
  src/index.css
  src/pages/Travel/TravelDetailPage.js
  src/stores/AppStore.js
Labels: développement, review

#332 customize carousel ans it's down
  .DS_Store
  .gitignore
  package.json
  src/components/Carousel.js
Labels: dév FRONT

#333 feat(travel): travel creation step 1
  src/App.js
  src/components/DatePicker.js
  src/pages/Travel/TravelCreationPage.js
  src/pages/Travel/TravelCreationPageOne.js
  src/pages/Travel/TravelCreationPageThree.js
  src/pages/Travel/TravelCreationPageTwo.js
  src/pages/Travel/TravelPage.js
  src/stores/TravelStore.js
Labels: review

#323 Add list item voyage + Correct Authentication Issues
  src/api/FirebaseRequestApi.js
  src/api/UserApi.js
  src/components/Button.js
  src/components/ImageUpload.js
  src/components/ListItemVoyage.js
  src/pages/Authentication/Login.js
  src/pages/Authentication/Registration.js
  src/pages/Travel/TravelPage.js
  src/stores/TravelStore.js
  src/stores/UserStore.js
  yarn.lock
Labels: review

#339 Front création voyage étape 1
  src/components/DatePicker.js
  src/components/Input.js
  src/pages/Travel/TravelCreationPage.js
  src/pages/Travel/TravelCreationPageOne.js
  yarn.lock
Labels: review

#324 feat(travel): Composant Sélection des Modules pour un voyage
  src/components/ModuleIcon.js
  src/components/SelectTravelModules.js
  src/components/TravelMenuDrawer.js
  src/index.css
Labels: Not merged, review

#342 224 back connexion - gestion erreurs
  src/pages/Authentication/Login.js
  src/stores/UserStore.js
  yarn.lock
Labels: review

#343 225 back inscription - ajout gestion erreurs sur page inscription
  src/components/ListItemSpending.js
  src/index.js
  src/pages/Authentication/Registration.js
  src/stores/UserStore.js
  yarn.lock
Labels: review

#345 fix(travel): travel creation and link to travel creation
  src/pages/Travel/TravelCreationPage.js
  src/pages/Travel/TravelCreationPageOne.js
  src/pages/Travel/TravelPage.js
  src/stores/TravelStore.js
Labels: review

#347 Correction des labels erreurs et vérification Inscription
  src/pages/Authentication/Registration.js
  src/stores/UserStore.js
Labels: review

#337 Front list item voyage
  src/components/Avatar.js
  src/components/Header.js
  src/components/ListItemVoyage.js
  src/pages/Authentication/Registration.js
  src/pages/Travel/TravelPage.js
  src/stores/UserStore.js
Labels: review

#350 Correction de la liste des voyages.
  src/components/Link.js
  src/components/ListItemVoyage.js
  src/pages/Travel/TravelDetailPage.js
  src/pages/Travel/TravelPage.js
Labels: review
