Repository InstitutG4/app-traveled, pull requests merged in 2018-03, with the labels that each got.

#172 Fix du clavier
  package.json
  src/components/ListeVoyagesComponent.js
  src/components/SignUpComponent.js
  src/components/authentification/style.js
  yarn.lock
Labels: enhancement

#180 Première version liste des listes
  Graphismes/Maquettes/Listes/liste_des_listes.png
Labels: maquette

#181 Première version maquette création liste
  Graphismes/Maquettes/Listes/Ajout_liste.png
Labels: maquette

#187 #138 #28 ajouter/modifier dépenses
  Graphismes/icônes/Ajout_Panier.svg
  Graphismes/icônes/Suppr_Panier.svg
  android/app/src/main/java/com/traveled/traveled/MainApplication.java
  package.json
  src/components/CreationDepenseComponent.js
  src/components/DepensesList.js
  src/components/MenuVoyageComponent.js
  src/router.js
  src/util.js
  yarn.lock
Labels: review

#190 115 supprimer un logement
  package.json
  src/components/ListeVoyagesComponent.js
  src/components/MenuVoyageComponent.js
  src/components/ModalButtonComponent.js
  src/components/ModalComponent.js
  src/screens/Housing/DetailsScreen.js
  src/screens/Housing/ListScreen.js
  src/stores/Housing.js
  yarn.lock
Labels: review

#186 Front accueil voyage
  src/components/MenuVoyageComponent.js
Labels: review

#173 FRONT & BACK : Ajouter logement
  package.json
  src/components/AddHousingComponent.js
  src/components/MenuVoyageComponent.js
  src/router.js
  src/screens/Housing/ListScreen.js
  src/stores/Housing.js
  yarn.lock
Labels: review

#210 Fix navigation et bouton de déconnexion
  src/components/AddHousingComponent.js
  src/components/CreationDepenseComponent.js
  src/components/ListeVoyagesComponent.js
Labels: review
